### ISSUE TITLE
Doesn't build with Brick 1.5/1.6

### ISSUE THREAD

**Issue by arrowd** [andys8/git-brunch#30]
GHC 9.2.7, cabal-install 3.10

```
[4 of 5] Compiling GitBrunch        ( app/GitBrunch.hs, /wrkdirs/usr/ports/devel/hs-git-brunch/work/git-brunch-1.6.0.0/dist-newstyle/build/x86_64-freebsd/ghc-9.2.7/git-brunch-1.6.0.0/x/git-brunch/build/git-brunch/git-brunch-tmp/GitBrunch.o )

app/GitBrunch.hs:61:23: error:
    * Expecting one more argument to `D.Dialog DialogOption'
      Expected a type, but `D.Dialog DialogOption' has kind `* -> *'
    * In the first argument of `Maybe', namely
        `(D.Dialog DialogOption)'
      In the type `Maybe (D.Dialog DialogOption)'
      In the definition of data constructor `State'
   |
61 |   , _dialog :: Maybe (D.Dialog DialogOption)
   |                       ^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build exe:git-brunch from git-brunch-1.6.0.0.
```

**Comment by andys8** [comment]
As you've probably noticed, the project is currently at [stackage snapshot 20.4](https://www.stackage.org/lts-20.4) (GHC 9.2.5, brick 1.4).

I plan to bump dependencies soon. Thanks for the hint 😉

**Comment by andys8** [comment]
I updated the repository to the latest lts stackage snapshot `lts-20.14` and GHC `9.2.7`. And there are now tests for cabal. https://github.com/andys8/git-brunch/pull/31

But brick is still in version `1.4` in this snapshot. Therefore I wanted to ask:
* Do you explicitly want to repository to work with `brick > 1.4`? Then it has to wait a bit.
* Or are you trying to build the project with GHC `9.2.7` and cabal? This would be expected to work.

**Comment by arrowd** [comment]
> Do you explicitly want to repository to work with brick > 1.4? Then it has to wait a bit.

Not really. I just tried `1.6` and `1.5` and then concluded that it doesn't work at all.

> Or are you trying to build the project with GHC 9.2.7 and cabal? This would be expected to work.

Yep, this is exactly the configuration I'm using. Good to hear it works!

**Comment by andys8** [comment]
Glad to hear. Closing, let me know in case you still encounter issues.
